environment:
  - PORT=3000
services:
  web:
    build: .
    port: 3000
    environment:
      - DD_AGENT_HOST=dd-agent.default.svc.cluster.local
    scale:
      count: 1-3
      targets:
        external:
          - name: "datadogmetric@default:page-views-metrics"
            averageValue: 5
